Repository googleapis/java-logging-servlet-initializer, pull requests merged in 2021-12, with the labels that each got.

#11 chore: fix dependency errors
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/snippet-bot.yml
  .github/workflows/approve-readme.yaml
  .github/workflows/samples.yaml
  .kokoro/readme.sh
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.sh
  CODE_OF_CONDUCT.md
  codecov.yaml
  java.header
  license-checks.xml
  pom.xml
  renovate.json
  samples/install-without-bom/pom.xml
  samples/pom.xml
  samples/snapshot/pom.xml
  samples/snippets/pom.xml
  src/test/java/com/google/cloud/logging/servlet/ContextCaptureInitializerTest.java
  src/test/java/com/google/cloud/logging/servlet/RequestContextFilterTest.java
  src/test/java/com/google/cloud/logging/servlet/it/ITContainersTest.java
Labels: cla: yes, api: logging

#13 Initial release
  pom.xml
  samples/install-without-bom/pom.xml
  samples/snapshot/pom.xml
  samples/snippets/pom.xml
Labels: api: logging

#15 chore: freeze web server dependency versions for IT
  owlbot.py
  renovate.json
Labels: api: logging

#16 chore: fix sample pom.xml dependencies
  samples/install-without-bom/pom.xml
  samples/snapshot/pom.xml
  samples/snippets/pom.xml
Labels: samples, api: logging

#17 chore: fix version typo
  samples/snippets/pom.xml
Labels: api: logging

#26 chore: add enumeration type of library
  .repo-metadata.json
Labels: automerge, api: logging
